name: Main CI

on: [push]

jobs: 
    run_tests:
        runs-on: ubuntu-latest
         
        environment: tests

        env:
            MAIN_URL: ${{ vars.MAIN_URL }}
        
        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.10.11

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip

            - name: Install poetry
              run: |
                pip install poetry 

            - name: Install project
              run: |
                poetry install 
            
            - name: Run Tests
              run: |
                poetry run pytest

            - name: Run mypy
              run: |
                poetry run mypy ./

            - name: Run pylint
              run: |
                poetry run pylint ./src


    build:
      runs-on: ubuntu-latest
        
      needs: [run_tests]
        
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: 'Docker login'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
  
        - name: Build and push to ACR
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: datasentics.azurecr.io/books:${{ github.sha }}
            file: Dockerfile
      
